---
title: "TKs test"
author: "Thomas Kilroy"
date: '`r Sys.Date()`'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r, echo=TRUE}
summary(cars)
```


```{r cols.print=3, rows.print=3}
mtcars
```

```{r}
mtcars
```
## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
plot(pressure)
```

```{r}
df_csv <- read_csv("https://www.opendatani.gov.uk/dataset/b278a287-0165-4b0d-ac06-f5356590355e/resource/9f4e090e-4afe-44f0-8bb5-1a70926920bd/download/regionalsedimentsxrfset1.csv") 
View(df_csv)
```

```{r}
install.packages(gapmingder)
library(gapminder)
df <- filter(gapminder, country == "Argentina") %>% 
  mutate(year = as.Date(paste(year, "-01-01", sep = "", format='%Y-%b-%d')))

ggplot(df, aes(x = year, y = lifeExp)) +
  geom_line(colour = "#fc6721", size = 1) +
  geom_point(colour = "#fc6721", size = 2) +
  scale_x_date(breaks = df$year, date_labels = "%Y") +
  scale_y_continuous(limits = c(0, max(df$lifeExp)), labels = scales::comma) +
  labs(title = "",
   subtitle = "Life expectancy in Argentina, 1952-2007",
   caption = "Source: Gapminder.org",
   x = "",
   y = "Age (years)") +
 theme_grey() +
  theme(panel.grid.major.x = element_blank())


```


```{r}
x <- c(1, 3, 4, 5)
y <- c(2, 6, 8, 10)
plot(x, y)}
```
